config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :users
  resources :drawings

  root'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/drawings_controller.rb
class DrawingsController < ApplicationController
 http_basic_authenticate_with name: "admin", password: "secret"
  def matchUser(user, matches)
      skips = Array.new
      while(user.match.empty? and not matches.empty?)
        match = matches.pop
        if(user.name != match[:name] and user.name != match[:partner])
          user.match = match[:name]
        else
          skips.append(match)
        end
      end
      skips.each {|skip| matches.push(skip) } 
      user.save
  end

  def index
    users = User.all
    matches = Array.new
    users.each {|user|
      user.match = ""
      matches.push({name: user.name, partner: user.partner})
    }
    matches = matches.shuffle
    users.each {|user|
      if user.partner.present?
        matchUser(user, matches)
      end
    }
    users.each {|user|
      if user.partner.empty?
        matchUser(user, matches)
      end
    }
    @drawings = users
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "secret", except: [:index, :show]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:name, :partner, :match)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drawings_helper.rb
module DrawingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/drawings/index.html.erb
<h1>Creating matches</h1>
<p>drawings.count = <%= @drawings.count %></p>
<table>
<% @drawings.each do |match| %>
    <tr>
      <td><%= match.name %></td>
      <td><%= match.match %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Return to Users', users_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecretSanta</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with model: @user, local: true do |form| %>
 
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :partner %><br>
    <%= form.text_field :partner %>
  </p>

  <p>
    <%= form.label :match %><br>
    <%= form.text_field :match %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/users/edit.html.erb
<h1>Edit Santa</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Secret Santas</h1>
<table>
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user_path(user),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<br/>
<%= link_to 'Add a Secret Santa', new_user_path %>
<br/>
<%= link_to 'Shuffle matches', drawings_path %>

app/views/users/new.html.erb
<h1>New Santa</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
 
<p>
  <strong>Match:</strong>
  <%= @user.match %>
</p>
 
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'Secret Santa', controller: 'users' %>